print('         ,r', end="");print("'",end="");print('"7')
print("r`-_   ,'  ,/")
print(' \. ". L_r', end=""); print("'")
print('   `~', end=""); print('\\', end=""); print('/')
print('      |')
print('      |')