print("     /~",end="");print('\\')
print("    ( oo|")
print("    _",end="");print('\\',end="");print("=/_")
print("   /  _  ",end="");print('\\')
print("  //|/.",end="");print("\\|\\\\")
print(" ||  \ /  ||")
print("============")
print("|          |")
print("|          |")
print("|          |")